# Generated by Django 6.0.3 on 2026-03-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='পূর্ণ নাম')),
                ('age', models.PositiveIntegerField(verbose_name='বয়স')),
                ('phone_number', models.CharField(max_length=11, verbose_name='ফোন নাম্বার')),
                ('email', models.EmailField(max_length=254, verbose_name='ইমেইল')),
                ('educational_qualification', models.CharField(choices=[('SSC', 'এসএসিি'), ('HSC', 'এইচএসসি'), ('Bachelor', 'স্নাতক'), ('Masters', 'স্নাতকোত্তর'), ('Other', 'অন্যান্য')], max_length=20, verbose_name='শিক্ষাগত যোগ্যতা')),
                ('programming_experience', models.CharField(choices=[('Beginner', 'শুরু করছি'), ('Intermediate', 'মধ্যম'), ('Advanced', 'উন্নত')], default='Beginner', max_length=20, verbose_name='প্রোগ্রামিং অভিজ্ঞতা')),
                ('message', models.TextField(blank=True, null=True, verbose_name='বার্তা বা প্রশ্ন')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='যোগদানের তারিখ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='শেষ পরিবর্তনের তারিখ')),
            ],
            options={
                'verbose_name': 'কোর্স রেজিস্ট্রেশন',
                'verbose_name_plural': 'কোর্স রেজিস্ট্রেশন সমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
