# Generated by Django 6.0.3 on 2026-03-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='ফোন নাম্বার'),
        ),
    ]
