# Generated by Django 6.0.3 on 2026-03-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_courseregistration_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False, help_text='Whether notification email has been sent')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/Device information')),
            ],
            options={
                'verbose_name': 'App Subscription',
                'verbose_name_plural': 'App Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
