# Generated by Django 6.0.3 on 2026-03-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.SlugField(editable=False, max_length=60, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(max_length=255)),
                ('short_title', models.TextField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('library_link', models.TextField(max_length=500)),
                ('how_to_use', models.TextField(blank=True, null=True)),
                ('is_for_libraries', models.BooleanField(default=True)),
                ('copy', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
