# Generated by Django 6.0.3 on 2026-03-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='copy',
        ),
        migrations.RemoveField(
            model_name='library',
            name='is_for_libraries',
        ),
        migrations.RemoveField(
            model_name='library',
            name='short_title',
        ),
        migrations.RemoveField(
            model_name='library',
            name='views',
        ),
    ]
