# Generated by Django 6.0.3 on 2026-03-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0002_remove_library_copy_remove_library_is_for_libraries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
